version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sistema_web
      POSTGRES_USER: username  # Match your .env file
      POSTGRES_PASSWORD: password  # Match your .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: